name: TheDodds
favicon: null
layout_spectrum: 0.8868227594066411
typography_spectrum: 0.8194198163691908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#82b1e0'
    - '#32517c'
    - '#7a5c42'
  brandStrength: 0.3669619292486459
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.45006020460277796
purpose: []
