name: TheDodds
favicon: null
layout_spectrum: 0.8868227594066411
typography_spectrum: 0.8194198163691908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3669619292486459
  lightness: 0.6633053193800151
  saturation: 0.5751895988360047
  rhythmicContrast: 0.45006020460277796
purpose: []
